doctrine:
    dbal:
        connections:
            default:
                dbname: '%env(DATABASE_NAME)%'
                driver: mysqli
                host: '%env(DATABASE_HOST)%'
                password: '%env(DATABASE_PASSWORD)%'
                user: '%env(DATABASE_USER)%'
                server_version: '8.0'
                charset: utf8mb4
                profiling_collect_backtrace: '%kernel.debug%'
                mapping_types:
                    enum: string
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    driver: pdo_sqlite
                    memory: true
                    host: ~
                    dbname: ~
                    user: ~
                    password: ~
                    server_version: '3.45'
                    charset: UTF8
                    mapping_types: []

when@prod:
    doctrine:
        orm:
            entity_managers:
                default:
                    query_cache_driver:
                        type: pool
                        pool: doctrine.system_cache_pool
                    result_cache_driver:
                        type: pool
                        pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
